// src/plugins/fontawesome.js
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Import des icônes que tu souhaites utiliser
import {
  faPlus,
  faTrash,
  faPencil,
  faInfoCircle,
  faUserCog,
  faTag,
  faShieldAlt,
  faPlusCircle,
  faCheckCircle,
  faArrowLeft,
  faSave,
  faLock,
  faExclamationTriangle,
  faUsers,
  faCalendar,
  faEnvelope,
  faShoppingCart,
  faUser,
  faHome,
  faBars,
  faUserCircle,
  faSignOutAlt,
  faCog,
  faBolt,
  faCashRegister,
  faReceipt,
  faBoxOpen,
  faUserShield,
  faChevronDown,
  faIdCard,
  faPrint,
  faLayerGroup,
} from '@fortawesome/free-solid-svg-icons'

// Ajoute les icônes dans la bibliothèque
library.add(
  faPlus,
  faTrash,
  faPencil,
  faInfoCircle,
  faUserCog,
  faTag,
  faShieldAlt,
  faPlusCircle,
  faCheckCircle,
  faArrowLeft,
  faSave,
  faLock,
  faExclamationTriangle,
  faUsers,
  faCalendar,
  faEnvelope,
  faShoppingCart,
  faUser,
  faHome,
  faBars,
  faUserCircle,
  faSignOutAlt,
  faCog,
  faBolt,
  faCashRegister,
  faReceipt,
  faBoxOpen,
  faUserShield,
  faChevronDown,
  faIdCard,
  faPrint,
  faLayerGroup,
)

export { FontAwesomeIcon }
